# Generated by Django 5.2.3 on 2025-06-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_blogs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='blogapp.blogpost'),
        ),
    ]
